### ISSUE TITLE
в просмотрщике jlcpcb видны не все дорожки

### ISSUE THREAD

**Issue by mzelenkin** [badenbaden/sls-gateway-din-rail#1]
При просмотре gerber'ов в просмотрщике jlcpcb не отображаются некоторые дорожки, например от +5V до стабилизатора. Проблема в gerber или просмотрщике jlcpcb?

**Comment by badenbaden** [comment]
Он бывает глючит. В маленьком варианте они видны, а при переходе на полный просмотр исчезают. Проверил в стороннем просмоторщике - все на месте.
https://ru.zofzpcb.com/ - программа просмотра герберов.
Вот скрин с нее:

![Screenshot_](https://user-images.githubusercontent.com/16225816/93722313-7dab3c00-fb9e-11ea-85f6-fac22f6545d8.png)

![Screenshot_(1)](https://user-images.githubusercontent.com/16225816/93722329-ae8b7100-fb9e-11ea-8a4f-cebb5ea0434d.png)

Как видно все на месте)).

**Comment by mzelenkin** [comment]
Это меня и смутило.
Благодарю за помощь!
